import java.util.Random;

public class MyRandom  extends Random {
    //Generated by Mathematica, m is a large prime that fits in the "long" range
    private static final long m = 1705533417848243881L; 
    private static final long a = 17; //Primitive root to m, calculated with Mathematica
    private static final long b = 0;
    private long seed;

    public MyRandom() {
        this(System.nanoTime());
    }

    public MyRandom(long seed) {
        this.seed = seed + 1; //seed should not be zero;
    }
    
}
